#pragma config(Motor,  port2,           motor1,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           motor2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           motor4,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           motor3,        tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int speed = 127;
	int delta = 10;

	int Btn8DPressed = 0;
	int Btn8UPressed = 0;
	int Btn8RPressed = 0;



	motor[motor1] = speed*1/4;
	motor[motor2] = speed*1/4;
	motor[motor3] = speed*1/4;
	motor[motor4] = speed*1/4;

	wait1Msec(250);

	motor[motor1] = speed*1/2;
	motor[motor2] = speed*1/2;
	motor[motor3] = speed*1/2;
	motor[motor4] = speed*1/2;

	wait1Msec(250);

	motor[motor1] = speed*3/4;
	motor[motor2] = speed*3/4;
	motor[motor3] = speed*3/4;
	motor[motor4] = speed*3/4;

	wait1Msec(250);

	while (1 == 1)
	{
		motor[motor1] = speed;
		motor[motor2] = speed;
		motor[motor3] = speed;
		motor[motor4] = speed;

	}

}
