#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           rightRearMotor, tmotorVex393_HBridge, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port2,           leftRearMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightLauncher, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           leftLauncher,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           intakeMotor,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rightFrontMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftFrontMotor, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int threshold = 10;
	int Btn5UToggleState = 0;
	int Btn5UPressed = 0;
	int Btn7UToggleState = 0;
	int Btn7UPressed = 0;
	int Btn7DToggleState = 0;
	int Btn7DPressed = 0;
	int speed = 75;

	while(1==1)
	{
		// DRIVE CONTROL - Tank drive style.
		//*******************************************************************
		if (abs(vexRT[Ch2]) > threshold)
		{
			motor[driveRightFront] = vexRT[Ch2];
			motor[driveRightBack] = vexRT[Ch2];
		}
		else
		{
			motor[driveRightFront] = 0;
			motor[driveRightBack] = 0;
		}
		if (abs(vexRT[Ch3]) > threshold)
		{
			motor[driveLeftFront] = vexRT[Ch3];
			motor[driveLeftBack] = vexRT[Ch3];
		}
		else
		{
			motor[driveLeftFront] = 0;
			motor[driveLeftBack] = 0;
		}

		// BALL LAUNCHER CONTROL - Shoots balls into goal.
		//*******************************************************************
		if (vexRT[Btn5U] == 1)
		{
			if (!Btn5UPressed)
			{
				Btn5UToggleState = 1 - Btn5UToggleState;
				Btn5UPressed = 1;
			}
		}
		else
		{
			Btn5UPressed = 0;
		}

		//=========================================

		// increase speed
		if (vexRT[Btn7U] == 1)
		{
			if (!Btn7UPressed)
			{
				Btn7UToggleState = 1 - Btn7UToggleState;
				Btn7UPressed = 1;
				if (Btn7UToggleState == 1)
				{
					speed = speed + 5;
				}
			}
		}
		else
		{
			Btn7UPressed = 0;
		}
		// decrease speed
		if (vexRT[Btn7D] == 1)
		{
			if (!Btn7DPressed)
			{
				Btn7DToggleState = 1 - Btn7DToggleState;
				Btn7DPressed = 1;
				if (Btn7DToggleState == 1)
				{
					speed = speed - 5;
				}
			}
		}
		else
		{
			Btn7DPressed = 0;
		}

		//DEFAULTSPEED
		if (vexRT[Btn8D])
		{
			speed = 75;
		}

		if (Btn5UToggleState)
		{
			motor[launcherLeftA] = speed;					//...activate launchers.
			motor[launcherLeftB] = speed;
			motor[launcherRightA] = speed;
			motor[launcherRightB] = speed;
		}
		else
		{
			motor[launcherLeftA] = 0;					//...deactivate launchers.
			motor[launcherLeftB] = 0;
			motor[launcherRightA] = 0;
			motor[launcherRightB] = 0;
		}


		// CHAIN INTAKE CONTROL - Lifts/stores balls and feeds to launcher.
		//*******************************************************************
		if (vexRT[Btn6U])
		{
			motor[hIntakeA] = 127;
			motor[hIntakeB] = 127;
		}
		else
		{
			motor[hIntakeA] = 0;
			motor[hIntakeB] = 0;
		}

	}
}
